package com.personal.hydra.ui.theme

import androidx.compose.ui.graphics.Color

// Brand seed: water teal.
val AquaTeal = Color(0xFF0E9F9B)

// ---------- LIGHT ----------
val LightPrimary = Color(0xFF006A6A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF6FF7F2)
val LightOnPrimaryContainer = Color(0xFF002020)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E7)
val LightOnSecondaryContainer = Color(0xFF051F1F)
val LightTertiary = Color(0xFFB8460E)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDBCD)
val LightOnTertiaryContainer = Color(0xFF3A0B00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBFA)
val LightOnBackground = Color(0xFF161D1D)
val LightSurface = Color(0xFFF4FBFA)
val LightOnSurface = Color(0xFF161D1D)
val LightSurfaceVariant = Color(0xFFDAE5E4)
val LightOnSurfaceVariant = Color(0xFF3F4948)
val LightOutline = Color(0xFF6F7978)
val LightOutlineVariant = Color(0xFFBEC9C8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFEEF5F4)
val LightSurfaceContainer = Color(0xFFE8EFEE)
val LightSurfaceContainerHigh = Color(0xFFE2EAE9)
val LightSurfaceContainerHighest = Color(0xFFDCE4E3)
val LightInverseSurface = Color(0xFF2B3231)
val LightInverseOnSurface = Color(0xFFECF2F1)
val LightInversePrimary = Color(0xFF4CDAD5)

// ---------- DARK (near-black, water accent) ----------
val DarkPrimary = Color(0xFF4CDAD5)
val DarkOnPrimary = Color(0xFF003736)
val DarkPrimaryContainer = Color(0xFF005250)
val DarkOnPrimaryContainer = Color(0xFF6FF7F2)
val DarkSecondary = Color(0xFFB0CCCB)
val DarkOnSecondary = Color(0xFF1B3535)
val DarkSecondaryContainer = Color(0xFF324B4B)
val DarkOnSecondaryContainer = Color(0xFFCCE8E7)
val DarkTertiary = Color(0xFFFFB59A)
val DarkOnTertiary = Color(0xFF5C1A00)
val DarkTertiaryContainer = Color(0xFF822C00)
val DarkOnTertiaryContainer = Color(0xFFFFDBCD)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF06090A)
val DarkOnBackground = Color(0xFFDDE4E3)
val DarkSurface = Color(0xFF06090A)
val DarkOnSurface = Color(0xFFC4CCCB)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBEC9C8)
val DarkOutline = Color(0xFF889392)
val DarkOutlineVariant = Color(0xFF3F4948)
val DarkSurfaceContainerLowest = Color(0xFF010404)
val DarkSurfaceContainerLow = Color(0xFF0E1313)
val DarkSurfaceContainer = Color(0xFF121817)
val DarkSurfaceContainerHigh = Color(0xFF1C2322)
val DarkSurfaceContainerHighest = Color(0xFF272E2D)
val DarkInverseSurface = Color(0xFFDDE4E3)
val DarkInverseOnSurface = Color(0xFF2B3231)
val DarkInversePrimary = Color(0xFF006A6A)
